sonar.projectKey=mukhammedsh_unisearch
sonar.organization=mukhammedsh

sonar.sources=backend/app,backend/scripts,backend/Dockerfile,frontend,scripts,.github
sonar.tests=backend/tests,tests

sonar.python.version=3.12
sonar.sourceEncoding=UTF-8

sonar.exclusions=backend/data/**,backend/data/university_assets/**,node_modules/**,release/**,frontend/Localization/**
sonar.test.inclusions=backend/tests/**,tests/**
